# coding=utf-8
# --------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for license information.
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is regenerated.
# --------------------------------------------------------------------------

from typing import TYPE_CHECKING

from azure.mgmt.core import ARMPipelineClient
from msrest import Deserializer, Serializer

if TYPE_CHECKING:
    # pylint: disable=unused-import,ungrouped-imports
    from typing import Any, Optional

    from azure.core.credentials import TokenCredential

from ._configuration import SecurityInsightsConfiguration
from .operations import AlertRulesOperations
from .operations import ActionsOperations
from .operations import AlertRuleTemplatesOperations
from .operations import AutomationRulesOperations
from .operations import IncidentsOperations
from .operations import BookmarksOperations
from .operations import BookmarkRelationsOperations
from .operations import BookmarkOperations
from .operations import IpGeodataOperations
from .operations import DomainWhoisOperations
from .operations import EntitiesOperations
from .operations import EntitiesGetTimelineOperations
from .operations import EntitiesRelationsOperations
from .operations import EntityRelationsOperations
from .operations import EntityQueriesOperations
from .operations import EntityQueryTemplatesOperations
from .operations import IncidentCommentsOperations
from .operations import IncidentRelationsOperations
from .operations import MetadataOperations
from .operations import OfficeConsentsOperations
from .operations import SentinelOnboardingStatesOperations
from .operations import SecurityMlAnalyticsSettingsOperations
from .operations import ProductSettingsOperations
from .operations import SourceControlOperations
from .operations import SourceControlsOperations
from .operations import ThreatIntelligenceIndicatorOperations
from .operations import ThreatIntelligenceIndicatorsOperations
from .operations import ThreatIntelligenceIndicatorMetricsOperations
from .operations import WatchlistsOperations
from .operations import WatchlistItemsOperations
from .operations import DataConnectorsOperations
from .operations import DataConnectorsCheckRequirementsOperations
from .operations import Operations
from . import models


class SecurityInsights(object):
    """API spec for Microsoft.SecurityInsights (Azure Security Insights) resource provider.

    :ivar alert_rules: AlertRulesOperations operations
    :vartype alert_rules: azure.mgmt.securityinsight.operations.AlertRulesOperations
    :ivar actions: ActionsOperations operations
    :vartype actions: azure.mgmt.securityinsight.operations.ActionsOperations
    :ivar alert_rule_templates: AlertRuleTemplatesOperations operations
    :vartype alert_rule_templates: azure.mgmt.securityinsight.operations.AlertRuleTemplatesOperations
    :ivar automation_rules: AutomationRulesOperations operations
    :vartype automation_rules: azure.mgmt.securityinsight.operations.AutomationRulesOperations
    :ivar incidents: IncidentsOperations operations
    :vartype incidents: azure.mgmt.securityinsight.operations.IncidentsOperations
    :ivar bookmarks: BookmarksOperations operations
    :vartype bookmarks: azure.mgmt.securityinsight.operations.BookmarksOperations
    :ivar bookmark_relations: BookmarkRelationsOperations operations
    :vartype bookmark_relations: azure.mgmt.securityinsight.operations.BookmarkRelationsOperations
    :ivar bookmark: BookmarkOperations operations
    :vartype bookmark: azure.mgmt.securityinsight.operations.BookmarkOperations
    :ivar ip_geodata: IpGeodataOperations operations
    :vartype ip_geodata: azure.mgmt.securityinsight.operations.IpGeodataOperations
    :ivar domain_whois: DomainWhoisOperations operations
    :vartype domain_whois: azure.mgmt.securityinsight.operations.DomainWhoisOperations
    :ivar entities: EntitiesOperations operations
    :vartype entities: azure.mgmt.securityinsight.operations.EntitiesOperations
    :ivar entities_get_timeline: EntitiesGetTimelineOperations operations
    :vartype entities_get_timeline: azure.mgmt.securityinsight.operations.EntitiesGetTimelineOperations
    :ivar entities_relations: EntitiesRelationsOperations operations
    :vartype entities_relations: azure.mgmt.securityinsight.operations.EntitiesRelationsOperations
    :ivar entity_relations: EntityRelationsOperations operations
    :vartype entity_relations: azure.mgmt.securityinsight.operations.EntityRelationsOperations
    :ivar entity_queries: EntityQueriesOperations operations
    :vartype entity_queries: azure.mgmt.securityinsight.operations.EntityQueriesOperations
    :ivar entity_query_templates: EntityQueryTemplatesOperations operations
    :vartype entity_query_templates: azure.mgmt.securityinsight.operations.EntityQueryTemplatesOperations
    :ivar incident_comments: IncidentCommentsOperations operations
    :vartype incident_comments: azure.mgmt.securityinsight.operations.IncidentCommentsOperations
    :ivar incident_relations: IncidentRelationsOperations operations
    :vartype incident_relations: azure.mgmt.securityinsight.operations.IncidentRelationsOperations
    :ivar metadata: MetadataOperations operations
    :vartype metadata: azure.mgmt.securityinsight.operations.MetadataOperations
    :ivar office_consents: OfficeConsentsOperations operations
    :vartype office_consents: azure.mgmt.securityinsight.operations.OfficeConsentsOperations
    :ivar sentinel_onboarding_states: SentinelOnboardingStatesOperations operations
    :vartype sentinel_onboarding_states: azure.mgmt.securityinsight.operations.SentinelOnboardingStatesOperations
    :ivar security_ml_analytics_settings: SecurityMlAnalyticsSettingsOperations operations
    :vartype security_ml_analytics_settings: azure.mgmt.securityinsight.operations.SecurityMlAnalyticsSettingsOperations
    :ivar product_settings: ProductSettingsOperations operations
    :vartype product_settings: azure.mgmt.securityinsight.operations.ProductSettingsOperations
    :ivar source_control: SourceControlOperations operations
    :vartype source_control: azure.mgmt.securityinsight.operations.SourceControlOperations
    :ivar source_controls: SourceControlsOperations operations
    :vartype source_controls: azure.mgmt.securityinsight.operations.SourceControlsOperations
    :ivar threat_intelligence_indicator: ThreatIntelligenceIndicatorOperations operations
    :vartype threat_intelligence_indicator: azure.mgmt.securityinsight.operations.ThreatIntelligenceIndicatorOperations
    :ivar threat_intelligence_indicators: ThreatIntelligenceIndicatorsOperations operations
    :vartype threat_intelligence_indicators: azure.mgmt.securityinsight.operations.ThreatIntelligenceIndicatorsOperations
    :ivar threat_intelligence_indicator_metrics: ThreatIntelligenceIndicatorMetricsOperations operations
    :vartype threat_intelligence_indicator_metrics: azure.mgmt.securityinsight.operations.ThreatIntelligenceIndicatorMetricsOperations
    :ivar watchlists: WatchlistsOperations operations
    :vartype watchlists: azure.mgmt.securityinsight.operations.WatchlistsOperations
    :ivar watchlist_items: WatchlistItemsOperations operations
    :vartype watchlist_items: azure.mgmt.securityinsight.operations.WatchlistItemsOperations
    :ivar data_connectors: DataConnectorsOperations operations
    :vartype data_connectors: azure.mgmt.securityinsight.operations.DataConnectorsOperations
    :ivar data_connectors_check_requirements: DataConnectorsCheckRequirementsOperations operations
    :vartype data_connectors_check_requirements: azure.mgmt.securityinsight.operations.DataConnectorsCheckRequirementsOperations
    :ivar operations: Operations operations
    :vartype operations: azure.mgmt.securityinsight.operations.Operations
    :param credential: Credential needed for the client to connect to Azure.
    :type credential: ~azure.core.credentials.TokenCredential
    :param subscription_id: The ID of the target subscription.
    :type subscription_id: str
    :param str base_url: Service URL
    """

    def __init__(
        self,
        credential,  # type: "TokenCredential"
        subscription_id,  # type: str
        base_url=None,  # type: Optional[str]
        **kwargs  # type: Any
    ):
        # type: (...) -> None
        if not base_url:
            base_url = 'https://management.azure.com'
        self._config = SecurityInsightsConfiguration(credential, subscription_id, **kwargs)
        self._client = ARMPipelineClient(base_url=base_url, config=self._config, **kwargs)

        client_models = {k: v for k, v in models.__dict__.items() if isinstance(v, type)}
        self._serialize = Serializer(client_models)
        self._serialize.client_side_validation = False
        self._deserialize = Deserializer(client_models)

        self.alert_rules = AlertRulesOperations(
            self._client, self._config, self._serialize, self._deserialize)
        self.actions = ActionsOperations(
            self._client, self._config, self._serialize, self._deserialize)
        self.alert_rule_templates = AlertRuleTemplatesOperations(
            self._client, self._config, self._serialize, self._deserialize)
        self.automation_rules = AutomationRulesOperations(
            self._client, self._config, self._serialize, self._deserialize)
        self.incidents = IncidentsOperations(
            self._client, self._config, self._serialize, self._deserialize)
        self.bookmarks = BookmarksOperations(
            self._client, self._config, self._serialize, self._deserialize)
        self.bookmark_relations = BookmarkRelationsOperations(
            self._client, self._config, self._serialize, self._deserialize)
        self.bookmark = BookmarkOperations(
            self._client, self._config, self._serialize, self._deserialize)
        self.ip_geodata = IpGeodataOperations(
            self._client, self._config, self._serialize, self._deserialize)
        self.domain_whois = DomainWhoisOperations(
            self._client, self._config, self._serialize, self._deserialize)
        self.entities = EntitiesOperations(
            self._client, self._config, self._serialize, self._deserialize)
        self.entities_get_timeline = EntitiesGetTimelineOperations(
            self._client, self._config, self._serialize, self._deserialize)
        self.entities_relations = EntitiesRelationsOperations(
            self._client, self._config, self._serialize, self._deserialize)
        self.entity_relations = EntityRelationsOperations(
            self._client, self._config, self._serialize, self._deserialize)
        self.entity_queries = EntityQueriesOperations(
            self._client, self._config, self._serialize, self._deserialize)
        self.entity_query_templates = EntityQueryTemplatesOperations(
            self._client, self._config, self._serialize, self._deserialize)
        self.incident_comments = IncidentCommentsOperations(
            self._client, self._config, self._serialize, self._deserialize)
        self.incident_relations = IncidentRelationsOperations(
            self._client, self._config, self._serialize, self._deserialize)
        self.metadata = MetadataOperations(
            self._client, self._config, self._serialize, self._deserialize)
        self.office_consents = OfficeConsentsOperations(
            self._client, self._config, self._serialize, self._deserialize)
        self.sentinel_onboarding_states = SentinelOnboardingStatesOperations(
            self._client, self._config, self._serialize, self._deserialize)
        self.security_ml_analytics_settings = SecurityMlAnalyticsSettingsOperations(
            self._client, self._config, self._serialize, self._deserialize)
        self.product_settings = ProductSettingsOperations(
            self._client, self._config, self._serialize, self._deserialize)
        self.source_control = SourceControlOperations(
            self._client, self._config, self._serialize, self._deserialize)
        self.source_controls = SourceControlsOperations(
            self._client, self._config, self._serialize, self._deserialize)
        self.threat_intelligence_indicator = ThreatIntelligenceIndicatorOperations(
            self._client, self._config, self._serialize, self._deserialize)
        self.threat_intelligence_indicators = ThreatIntelligenceIndicatorsOperations(
            self._client, self._config, self._serialize, self._deserialize)
        self.threat_intelligence_indicator_metrics = ThreatIntelligenceIndicatorMetricsOperations(
            self._client, self._config, self._serialize, self._deserialize)
        self.watchlists = WatchlistsOperations(
            self._client, self._config, self._serialize, self._deserialize)
        self.watchlist_items = WatchlistItemsOperations(
            self._client, self._config, self._serialize, self._deserialize)
        self.data_connectors = DataConnectorsOperations(
            self._client, self._config, self._serialize, self._deserialize)
        self.data_connectors_check_requirements = DataConnectorsCheckRequirementsOperations(
            self._client, self._config, self._serialize, self._deserialize)
        self.operations = Operations(
            self._client, self._config, self._serialize, self._deserialize)

    def close(self):
        # type: () -> None
        self._client.close()

    def __enter__(self):
        # type: () -> SecurityInsights
        self._client.__enter__()
        return self

    def __exit__(self, *exc_details):
        # type: (Any) -> None
        self._client.__exit__(*exc_details)
