# --------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for
# license information.
#
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------
# pylint: disable=too-many-lines
# pylint: disable=too-many-statements

from azure.cli.core.commands.parameters import get_enum_type


def load_arguments(self, _):
    with self.argument_context('sentinel automation-rule create') as c:
        c.argument('triggers_when', arg_type=get_enum_type(['Created', 'Updated']), help='When the automation rule is '
                   'triggered', arg_group='Triggering Logic')

    with self.argument_context('sentinel automation-rule update') as c:
        c.argument('triggers_when', arg_type=get_enum_type(['Created', 'Updated']), help='When the automation rule is '
                   'triggered', arg_group='Triggering Logic')

    with self.argument_context('sentinel incident run-playbook') as c:
        c.argument('incident_identifier', type=str, help='Identifier of incident.', id_part='child_name_1')
        c.argument('tenant_id', help='ID of tenant.')
        c.argument('logic_apps_resource_id', type=str, help='Resource ID of logic apps.')
