# coding=utf-8
# --------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for license information.
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is regenerated.
# --------------------------------------------------------------------------

try:
    from ._models_py3 import AadCheckRequirements
    from ._models_py3 import AadCheckRequirementsProperties
    from ._models_py3 import AadDataConnector
    from ._models_py3 import AadDataConnectorProperties
    from ._models_py3 import AatpCheckRequirements
    from ._models_py3 import AatpCheckRequirementsProperties
    from ._models_py3 import AatpDataConnector
    from ._models_py3 import AatpDataConnectorProperties
    from ._models_py3 import AccountEntity
    from ._models_py3 import AccountEntityProperties
    from ._models_py3 import ActionPropertiesBase
    from ._models_py3 import ActionRequest
    from ._models_py3 import ActionRequestProperties
    from ._models_py3 import ActionResponse
    from ._models_py3 import ActionResponseProperties
    from ._models_py3 import ActionsList
    from ._models_py3 import ActivityCustomEntityQuery
    from ._models_py3 import ActivityEntityQueriesPropertiesQueryDefinitions
    from ._models_py3 import ActivityEntityQuery
    from ._models_py3 import ActivityEntityQueryTemplate
    from ._models_py3 import ActivityEntityQueryTemplatePropertiesQueryDefinitions
    from ._models_py3 import ActivityTimelineItem
    from ._models_py3 import AlertDetailsOverride
    from ._models_py3 import AlertRule
    from ._models_py3 import AlertRuleTemplate
    from ._models_py3 import AlertRuleTemplateDataSource
    from ._models_py3 import AlertRuleTemplatePropertiesBase
    from ._models_py3 import AlertRuleTemplateWithMitreProperties
    from ._models_py3 import AlertRuleTemplatesList
    from ._models_py3 import AlertRulesList
    from ._models_py3 import AlertsDataTypeOfDataConnector
    from ._models_py3 import Anomalies
    from ._models_py3 import AnomalySecurityMlAnalyticsSettings
    from ._models_py3 import AnomalyTimelineItem
    from ._models_py3 import AscCheckRequirements
    from ._models_py3 import AscDataConnector
    from ._models_py3 import AscDataConnectorProperties
    from ._models_py3 import AutomationRule
    from ._models_py3 import AutomationRuleAction
    from ._models_py3 import AutomationRuleCondition
    from ._models_py3 import AutomationRuleModifyPropertiesAction
    from ._models_py3 import AutomationRulePropertyArrayChangedValuesCondition
    from ._models_py3 import AutomationRulePropertyValuesChangedCondition
    from ._models_py3 import AutomationRulePropertyValuesCondition
    from ._models_py3 import AutomationRuleRunPlaybookAction
    from ._models_py3 import AutomationRuleTriggeringLogic
    from ._models_py3 import AutomationRulesList
    from ._models_py3 import Availability
    from ._models_py3 import AwsCloudTrailCheckRequirements
    from ._models_py3 import AwsCloudTrailDataConnector
    from ._models_py3 import AwsCloudTrailDataConnectorDataTypes
    from ._models_py3 import AwsCloudTrailDataConnectorDataTypesLogs
    from ._models_py3 import AwsS3CheckRequirements
    from ._models_py3 import AwsS3DataConnector
    from ._models_py3 import AwsS3DataConnectorDataTypes
    from ._models_py3 import AwsS3DataConnectorDataTypesLogs
    from ._models_py3 import AzureDevOpsResourceInfo
    from ._models_py3 import AzureResourceEntity
    from ._models_py3 import AzureResourceEntityProperties
    from ._models_py3 import Bookmark
    from ._models_py3 import BookmarkEntityMappings
    from ._models_py3 import BookmarkExpandParameters
    from ._models_py3 import BookmarkExpandResponse
    from ._models_py3 import BookmarkExpandResponseValue
    from ._models_py3 import BookmarkList
    from ._models_py3 import BookmarkTimelineItem
    from ._models_py3 import ClientInfo
    from ._models_py3 import CloudApplicationEntity
    from ._models_py3 import CloudApplicationEntityProperties
    from ._models_py3 import CloudErrorBody
    from ._models_py3 import CodelessApiPollingDataConnector
    from ._models_py3 import CodelessConnectorPollingAuthProperties
    from ._models_py3 import CodelessConnectorPollingConfigProperties
    from ._models_py3 import CodelessConnectorPollingPagingProperties
    from ._models_py3 import CodelessConnectorPollingRequestProperties
    from ._models_py3 import CodelessConnectorPollingResponseProperties
    from ._models_py3 import CodelessUiConnectorConfigProperties
    from ._models_py3 import CodelessUiConnectorConfigPropertiesConnectivityCriteriaItem
    from ._models_py3 import CodelessUiConnectorConfigPropertiesDataTypesItem
    from ._models_py3 import CodelessUiConnectorConfigPropertiesGraphQueriesItem
    from ._models_py3 import CodelessUiConnectorConfigPropertiesInstructionStepsItem
    from ._models_py3 import CodelessUiConnectorConfigPropertiesSampleQueriesItem
    from ._models_py3 import CodelessUiDataConnector
    from ._models_py3 import ConnectedEntity
    from ._models_py3 import ConnectivityCriteria
    from ._models_py3 import ConnectorInstructionModelBase
    from ._models_py3 import ContentPathMap
    from ._models_py3 import CustomEntityQuery
    from ._models_py3 import Customs
    from ._models_py3 import CustomsPermission
    from ._models_py3 import DataConnector
    from ._models_py3 import DataConnectorConnectBody
    from ._models_py3 import DataConnectorDataTypeCommon
    from ._models_py3 import DataConnectorList
    from ._models_py3 import DataConnectorRequirementsState
    from ._models_py3 import DataConnectorTenantId
    from ._models_py3 import DataConnectorWithAlertsProperties
    from ._models_py3 import DataConnectorsCheckRequirements
    from ._models_py3 import DataTypeDefinitions
    from ._models_py3 import Deployment
    from ._models_py3 import DeploymentInfo
    from ._models_py3 import DnsEntity
    from ._models_py3 import DnsEntityProperties
    from ._models_py3 import Dynamics365CheckRequirements
    from ._models_py3 import Dynamics365CheckRequirementsProperties
    from ._models_py3 import Dynamics365DataConnector
    from ._models_py3 import Dynamics365DataConnectorDataTypes
    from ._models_py3 import Dynamics365DataConnectorDataTypesDynamics365CdsActivities
    from ._models_py3 import Dynamics365DataConnectorProperties
    from ._models_py3 import EnrichmentDomainWhois
    from ._models_py3 import EnrichmentDomainWhoisContact
    from ._models_py3 import EnrichmentDomainWhoisContacts
    from ._models_py3 import EnrichmentDomainWhoisDetails
    from ._models_py3 import EnrichmentDomainWhoisRegistrarDetails
    from ._models_py3 import EnrichmentIpGeodata
    from ._models_py3 import Entity
    from ._models_py3 import EntityAnalytics
    from ._models_py3 import EntityCommonProperties
    from ._models_py3 import EntityEdges
    from ._models_py3 import EntityExpandParameters
    from ._models_py3 import EntityExpandResponse
    from ._models_py3 import EntityExpandResponseValue
    from ._models_py3 import EntityFieldMapping
    from ._models_py3 import EntityGetInsightsParameters
    from ._models_py3 import EntityGetInsightsResponse
    from ._models_py3 import EntityInsightItem
    from ._models_py3 import EntityInsightItemQueryTimeInterval
    from ._models_py3 import EntityList
    from ._models_py3 import EntityMapping
    from ._models_py3 import EntityQuery
    from ._models_py3 import EntityQueryItem
    from ._models_py3 import EntityQueryItemProperties
    from ._models_py3 import EntityQueryItemPropertiesDataTypesItem
    from ._models_py3 import EntityQueryList
    from ._models_py3 import EntityQueryTemplate
    from ._models_py3 import EntityQueryTemplateList
    from ._models_py3 import EntityTimelineItem
    from ._models_py3 import EntityTimelineParameters
    from ._models_py3 import EntityTimelineResponse
    from ._models_py3 import EventGroupingSettings
    from ._models_py3 import ExpansionEntityQuery
    from ._models_py3 import ExpansionResultAggregation
    from ._models_py3 import ExpansionResultsMetadata
    from ._models_py3 import EyesOn
    from ._models_py3 import FieldMapping
    from ._models_py3 import FileEntity
    from ._models_py3 import FileEntityProperties
    from ._models_py3 import FileHashEntity
    from ._models_py3 import FileHashEntityProperties
    from ._models_py3 import FusionAlertRule
    from ._models_py3 import FusionAlertRuleTemplate
    from ._models_py3 import FusionScenarioExclusionPattern
    from ._models_py3 import FusionSourceSettings
    from ._models_py3 import FusionSourceSubTypeSetting
    from ._models_py3 import FusionSubTypeSeverityFilter
    from ._models_py3 import FusionSubTypeSeverityFiltersItem
    from ._models_py3 import FusionTemplateSourceSetting
    from ._models_py3 import FusionTemplateSourceSubType
    from ._models_py3 import FusionTemplateSubTypeSeverityFilter
    from ._models_py3 import GeoLocation
    from ._models_py3 import GetInsightsErrorKind
    from ._models_py3 import GetInsightsResultsMetadata
    from ._models_py3 import GetQueriesResponse
    from ._models_py3 import GitHubResourceInfo
    from ._models_py3 import GraphQueries
    from ._models_py3 import GroupingConfiguration
    from ._models_py3 import HostEntity
    from ._models_py3 import HostEntityProperties
    from ._models_py3 import HuntingBookmark
    from ._models_py3 import HuntingBookmarkProperties
    from ._models_py3 import Incident
    from ._models_py3 import IncidentAdditionalData
    from ._models_py3 import IncidentAlertList
    from ._models_py3 import IncidentBookmarkList
    from ._models_py3 import IncidentComment
    from ._models_py3 import IncidentCommentList
    from ._models_py3 import IncidentConfiguration
    from ._models_py3 import IncidentEntitiesResponse
    from ._models_py3 import IncidentEntitiesResultsMetadata
    from ._models_py3 import IncidentInfo
    from ._models_py3 import IncidentLabel
    from ._models_py3 import IncidentList
    from ._models_py3 import IncidentOwnerInfo
    from ._models_py3 import IncidentPropertiesAction
    from ._models_py3 import InsightQueryItem
    from ._models_py3 import InsightQueryItemProperties
    from ._models_py3 import InsightQueryItemPropertiesAdditionalQuery
    from ._models_py3 import InsightQueryItemPropertiesDefaultTimeRange
    from ._models_py3 import InsightQueryItemPropertiesReferenceTimeRange
    from ._models_py3 import InsightQueryItemPropertiesTableQuery
    from ._models_py3 import InsightQueryItemPropertiesTableQueryColumnsDefinitionsItem
    from ._models_py3 import InsightQueryItemPropertiesTableQueryQueriesDefinitionsItem
    from ._models_py3 import InsightQueryItemPropertiesTableQueryQueriesDefinitionsPropertiesItemsItem
    from ._models_py3 import InsightsTableResult
    from ._models_py3 import InsightsTableResultColumnsItem
    from ._models_py3 import InstructionSteps
    from ._models_py3 import InstructionStepsInstructionsItem
    from ._models_py3 import IoTCheckRequirements
    from ._models_py3 import IoTDataConnector
    from ._models_py3 import IoTDataConnectorProperties
    from ._models_py3 import IoTDeviceEntity
    from ._models_py3 import IoTDeviceEntityProperties
    from ._models_py3 import IpEntity
    from ._models_py3 import IpEntityProperties
    from ._models_py3 import LastDataReceivedDataType
    from ._models_py3 import MailClusterEntity
    from ._models_py3 import MailClusterEntityProperties
    from ._models_py3 import MailMessageEntity
    from ._models_py3 import MailMessageEntityProperties
    from ._models_py3 import MailboxEntity
    from ._models_py3 import MailboxEntityProperties
    from ._models_py3 import MalwareEntity
    from ._models_py3 import MalwareEntityProperties
    from ._models_py3 import ManualTriggerRequestBody
    from ._models_py3 import McasCheckRequirements
    from ._models_py3 import McasCheckRequirementsProperties
    from ._models_py3 import McasDataConnector
    from ._models_py3 import McasDataConnectorDataTypes
    from ._models_py3 import McasDataConnectorProperties
    from ._models_py3 import MdatpCheckRequirements
    from ._models_py3 import MdatpCheckRequirementsProperties
    from ._models_py3 import MdatpDataConnector
    from ._models_py3 import MdatpDataConnectorProperties
    from ._models_py3 import MetadataAuthor
    from ._models_py3 import MetadataCategories
    from ._models_py3 import MetadataDependencies
    from ._models_py3 import MetadataList
    from ._models_py3 import MetadataModel
    from ._models_py3 import MetadataPatch
    from ._models_py3 import MetadataSource
    from ._models_py3 import MetadataSupport
    from ._models_py3 import MicrosoftSecurityIncidentCreationAlertRule
    from ._models_py3 import MicrosoftSecurityIncidentCreationAlertRuleCommonProperties
    from ._models_py3 import MicrosoftSecurityIncidentCreationAlertRuleProperties
    from ._models_py3 import MicrosoftSecurityIncidentCreationAlertRuleTemplate
    from ._models_py3 import MicrosoftSecurityIncidentCreationAlertRuleTemplateProperties
    from ._models_py3 import MlBehaviorAnalyticsAlertRule
    from ._models_py3 import MlBehaviorAnalyticsAlertRuleTemplate
    from ._models_py3 import MlBehaviorAnalyticsAlertRuleTemplateProperties
    from ._models_py3 import MstiCheckRequirements
    from ._models_py3 import MstiCheckRequirementsProperties
    from ._models_py3 import MstiDataConnector
    from ._models_py3 import MstiDataConnectorDataTypes
    from ._models_py3 import MstiDataConnectorDataTypesBingSafetyPhishingUrl
    from ._models_py3 import MstiDataConnectorDataTypesMicrosoftEmergingThreatFeed
    from ._models_py3 import MstiDataConnectorProperties
    from ._models_py3 import MtpCheckRequirements
    from ._models_py3 import MtpCheckRequirementsProperties
    from ._models_py3 import MtpDataConnector
    from ._models_py3 import MtpDataConnectorDataTypes
    from ._models_py3 import MtpDataConnectorDataTypesIncidents
    from ._models_py3 import MtpDataConnectorProperties
    from ._models_py3 import NrtAlertRule
    from ._models_py3 import NrtAlertRuleTemplate
    from ._models_py3 import NrtAlertRuleTemplateProperties
    from ._models_py3 import Office365ProjectCheckRequirements
    from ._models_py3 import Office365ProjectCheckRequirementsProperties
    from ._models_py3 import Office365ProjectConnectorDataTypes
    from ._models_py3 import Office365ProjectConnectorDataTypesLogs
    from ._models_py3 import Office365ProjectDataConnector
    from ._models_py3 import Office365ProjectDataConnectorProperties
    from ._models_py3 import OfficeAtpCheckRequirements
    from ._models_py3 import OfficeAtpCheckRequirementsProperties
    from ._models_py3 import OfficeAtpDataConnector
    from ._models_py3 import OfficeAtpDataConnectorProperties
    from ._models_py3 import OfficeConsent
    from ._models_py3 import OfficeConsentList
    from ._models_py3 import OfficeDataConnector
    from ._models_py3 import OfficeDataConnectorDataTypes
    from ._models_py3 import OfficeDataConnectorDataTypesExchange
    from ._models_py3 import OfficeDataConnectorDataTypesSharePoint
    from ._models_py3 import OfficeDataConnectorDataTypesTeams
    from ._models_py3 import OfficeDataConnectorProperties
    from ._models_py3 import OfficeIrmCheckRequirements
    from ._models_py3 import OfficeIrmCheckRequirementsProperties
    from ._models_py3 import OfficeIrmDataConnector
    from ._models_py3 import OfficeIrmDataConnectorProperties
    from ._models_py3 import OfficePowerBiCheckRequirements
    from ._models_py3 import OfficePowerBiCheckRequirementsProperties
    from ._models_py3 import OfficePowerBiConnectorDataTypes
    from ._models_py3 import OfficePowerBiConnectorDataTypesLogs
    from ._models_py3 import OfficePowerBiDataConnector
    from ._models_py3 import OfficePowerBiDataConnectorProperties
    from ._models_py3 import Operation
    from ._models_py3 import OperationDisplay
    from ._models_py3 import OperationsList
    from ._models_py3 import Permissions
    from ._models_py3 import PermissionsCustomsItem
    from ._models_py3 import PermissionsResourceProviderItem
    from ._models_py3 import PlaybookActionProperties
    from ._models_py3 import ProcessEntity
    from ._models_py3 import ProcessEntityProperties
    from ._models_py3 import PropertyArrayChangedConditionProperties
    from ._models_py3 import PropertyChangedConditionProperties
    from ._models_py3 import PropertyConditionProperties
    from ._models_py3 import QueryBasedAlertRuleTemplateProperties
    from ._models_py3 import RegistryKeyEntity
    from ._models_py3 import RegistryKeyEntityProperties
    from ._models_py3 import RegistryValueEntity
    from ._models_py3 import RegistryValueEntityProperties
    from ._models_py3 import Relation
    from ._models_py3 import RelationList
    from ._models_py3 import Repo
    from ._models_py3 import RepoList
    from ._models_py3 import Repository
    from ._models_py3 import RepositoryResourceInfo
    from ._models_py3 import RequiredPermissions
    from ._models_py3 import Resource
    from ._models_py3 import ResourceProvider
    from ._models_py3 import ResourceWithEtag
    from ._models_py3 import SampleQueries
    from ._models_py3 import ScheduledAlertRule
    from ._models_py3 import ScheduledAlertRuleCommonProperties
    from ._models_py3 import ScheduledAlertRuleProperties
    from ._models_py3 import ScheduledAlertRuleTemplate
    from ._models_py3 import SecurityAlert
    from ._models_py3 import SecurityAlertProperties
    from ._models_py3 import SecurityAlertPropertiesConfidenceReasonsItem
    from ._models_py3 import SecurityAlertTimelineItem
    from ._models_py3 import SecurityGroupEntity
    from ._models_py3 import SecurityGroupEntityProperties
    from ._models_py3 import SecurityMlAnalyticsSetting
    from ._models_py3 import SecurityMlAnalyticsSettingsDataSource
    from ._models_py3 import SecurityMlAnalyticsSettingsList
    from ._models_py3 import SentinelOnboardingState
    from ._models_py3 import SentinelOnboardingStatesList
    from ._models_py3 import SettingList
    from ._models_py3 import Settings
    from ._models_py3 import SourceControl
    from ._models_py3 import SourceControlList
    from ._models_py3 import SubmissionMailEntity
    from ._models_py3 import SubmissionMailEntityProperties
    from ._models_py3 import SystemData
    from ._models_py3 import TeamInformation
    from ._models_py3 import TeamProperties
    from ._models_py3 import ThreatIntelligence
    from ._models_py3 import ThreatIntelligenceAlertRule
    from ._models_py3 import ThreatIntelligenceAlertRuleTemplate
    from ._models_py3 import ThreatIntelligenceAlertRuleTemplateProperties
    from ._models_py3 import ThreatIntelligenceAppendTags
    from ._models_py3 import ThreatIntelligenceExternalReference
    from ._models_py3 import ThreatIntelligenceFilteringCriteria
    from ._models_py3 import ThreatIntelligenceGranularMarkingModel
    from ._models_py3 import ThreatIntelligenceIndicatorModel
    from ._models_py3 import ThreatIntelligenceIndicatorProperties
    from ._models_py3 import ThreatIntelligenceInformation
    from ._models_py3 import ThreatIntelligenceInformationList
    from ._models_py3 import ThreatIntelligenceKillChainPhase
    from ._models_py3 import ThreatIntelligenceMetric
    from ._models_py3 import ThreatIntelligenceMetricEntity
    from ._models_py3 import ThreatIntelligenceMetrics
    from ._models_py3 import ThreatIntelligenceMetricsList
    from ._models_py3 import ThreatIntelligenceParsedPattern
    from ._models_py3 import ThreatIntelligenceParsedPatternTypeValue
    from ._models_py3 import ThreatIntelligenceSortingCriteria
    from ._models_py3 import TiCheckRequirements
    from ._models_py3 import TiCheckRequirementsProperties
    from ._models_py3 import TiDataConnector
    from ._models_py3 import TiDataConnectorDataTypes
    from ._models_py3 import TiDataConnectorDataTypesIndicators
    from ._models_py3 import TiDataConnectorProperties
    from ._models_py3 import TiTaxiiCheckRequirements
    from ._models_py3 import TiTaxiiCheckRequirementsProperties
    from ._models_py3 import TiTaxiiDataConnector
    from ._models_py3 import TiTaxiiDataConnectorDataTypes
    from ._models_py3 import TiTaxiiDataConnectorDataTypesTaxiiClient
    from ._models_py3 import TiTaxiiDataConnectorProperties
    from ._models_py3 import TimelineAggregation
    from ._models_py3 import TimelineError
    from ._models_py3 import TimelineResultsMetadata
    from ._models_py3 import Ueba
    from ._models_py3 import UrlEntity
    from ._models_py3 import UrlEntityProperties
    from ._models_py3 import UserInfo
    from ._models_py3 import Watchlist
    from ._models_py3 import WatchlistItem
    from ._models_py3 import WatchlistItemList
    from ._models_py3 import WatchlistList
    from ._models_py3 import Webhook
except (SyntaxError, ImportError):
    from ._models import AadCheckRequirements  # type: ignore
    from ._models import AadCheckRequirementsProperties  # type: ignore
    from ._models import AadDataConnector  # type: ignore
    from ._models import AadDataConnectorProperties  # type: ignore
    from ._models import AatpCheckRequirements  # type: ignore
    from ._models import AatpCheckRequirementsProperties  # type: ignore
    from ._models import AatpDataConnector  # type: ignore
    from ._models import AatpDataConnectorProperties  # type: ignore
    from ._models import AccountEntity  # type: ignore
    from ._models import AccountEntityProperties  # type: ignore
    from ._models import ActionPropertiesBase  # type: ignore
    from ._models import ActionRequest  # type: ignore
    from ._models import ActionRequestProperties  # type: ignore
    from ._models import ActionResponse  # type: ignore
    from ._models import ActionResponseProperties  # type: ignore
    from ._models import ActionsList  # type: ignore
    from ._models import ActivityCustomEntityQuery  # type: ignore
    from ._models import ActivityEntityQueriesPropertiesQueryDefinitions  # type: ignore
    from ._models import ActivityEntityQuery  # type: ignore
    from ._models import ActivityEntityQueryTemplate  # type: ignore
    from ._models import ActivityEntityQueryTemplatePropertiesQueryDefinitions  # type: ignore
    from ._models import ActivityTimelineItem  # type: ignore
    from ._models import AlertDetailsOverride  # type: ignore
    from ._models import AlertRule  # type: ignore
    from ._models import AlertRuleTemplate  # type: ignore
    from ._models import AlertRuleTemplateDataSource  # type: ignore
    from ._models import AlertRuleTemplatePropertiesBase  # type: ignore
    from ._models import AlertRuleTemplateWithMitreProperties  # type: ignore
    from ._models import AlertRuleTemplatesList  # type: ignore
    from ._models import AlertRulesList  # type: ignore
    from ._models import AlertsDataTypeOfDataConnector  # type: ignore
    from ._models import Anomalies  # type: ignore
    from ._models import AnomalySecurityMlAnalyticsSettings  # type: ignore
    from ._models import AnomalyTimelineItem  # type: ignore
    from ._models import AscCheckRequirements  # type: ignore
    from ._models import AscDataConnector  # type: ignore
    from ._models import AscDataConnectorProperties  # type: ignore
    from ._models import AutomationRule  # type: ignore
    from ._models import AutomationRuleAction  # type: ignore
    from ._models import AutomationRuleCondition  # type: ignore
    from ._models import AutomationRuleModifyPropertiesAction  # type: ignore
    from ._models import AutomationRulePropertyArrayChangedValuesCondition  # type: ignore
    from ._models import AutomationRulePropertyValuesChangedCondition  # type: ignore
    from ._models import AutomationRulePropertyValuesCondition  # type: ignore
    from ._models import AutomationRuleRunPlaybookAction  # type: ignore
    from ._models import AutomationRuleTriggeringLogic  # type: ignore
    from ._models import AutomationRulesList  # type: ignore
    from ._models import Availability  # type: ignore
    from ._models import AwsCloudTrailCheckRequirements  # type: ignore
    from ._models import AwsCloudTrailDataConnector  # type: ignore
    from ._models import AwsCloudTrailDataConnectorDataTypes  # type: ignore
    from ._models import AwsCloudTrailDataConnectorDataTypesLogs  # type: ignore
    from ._models import AwsS3CheckRequirements  # type: ignore
    from ._models import AwsS3DataConnector  # type: ignore
    from ._models import AwsS3DataConnectorDataTypes  # type: ignore
    from ._models import AwsS3DataConnectorDataTypesLogs  # type: ignore
    from ._models import AzureDevOpsResourceInfo  # type: ignore
    from ._models import AzureResourceEntity  # type: ignore
    from ._models import AzureResourceEntityProperties  # type: ignore
    from ._models import Bookmark  # type: ignore
    from ._models import BookmarkEntityMappings  # type: ignore
    from ._models import BookmarkExpandParameters  # type: ignore
    from ._models import BookmarkExpandResponse  # type: ignore
    from ._models import BookmarkExpandResponseValue  # type: ignore
    from ._models import BookmarkList  # type: ignore
    from ._models import BookmarkTimelineItem  # type: ignore
    from ._models import ClientInfo  # type: ignore
    from ._models import CloudApplicationEntity  # type: ignore
    from ._models import CloudApplicationEntityProperties  # type: ignore
    from ._models import CloudErrorBody  # type: ignore
    from ._models import CodelessApiPollingDataConnector  # type: ignore
    from ._models import CodelessConnectorPollingAuthProperties  # type: ignore
    from ._models import CodelessConnectorPollingConfigProperties  # type: ignore
    from ._models import CodelessConnectorPollingPagingProperties  # type: ignore
    from ._models import CodelessConnectorPollingRequestProperties  # type: ignore
    from ._models import CodelessConnectorPollingResponseProperties  # type: ignore
    from ._models import CodelessUiConnectorConfigProperties  # type: ignore
    from ._models import CodelessUiConnectorConfigPropertiesConnectivityCriteriaItem  # type: ignore
    from ._models import CodelessUiConnectorConfigPropertiesDataTypesItem  # type: ignore
    from ._models import CodelessUiConnectorConfigPropertiesGraphQueriesItem  # type: ignore
    from ._models import CodelessUiConnectorConfigPropertiesInstructionStepsItem  # type: ignore
    from ._models import CodelessUiConnectorConfigPropertiesSampleQueriesItem  # type: ignore
    from ._models import CodelessUiDataConnector  # type: ignore
    from ._models import ConnectedEntity  # type: ignore
    from ._models import ConnectivityCriteria  # type: ignore
    from ._models import ConnectorInstructionModelBase  # type: ignore
    from ._models import ContentPathMap  # type: ignore
    from ._models import CustomEntityQuery  # type: ignore
    from ._models import Customs  # type: ignore
    from ._models import CustomsPermission  # type: ignore
    from ._models import DataConnector  # type: ignore
    from ._models import DataConnectorConnectBody  # type: ignore
    from ._models import DataConnectorDataTypeCommon  # type: ignore
    from ._models import DataConnectorList  # type: ignore
    from ._models import DataConnectorRequirementsState  # type: ignore
    from ._models import DataConnectorTenantId  # type: ignore
    from ._models import DataConnectorWithAlertsProperties  # type: ignore
    from ._models import DataConnectorsCheckRequirements  # type: ignore
    from ._models import DataTypeDefinitions  # type: ignore
    from ._models import Deployment  # type: ignore
    from ._models import DeploymentInfo  # type: ignore
    from ._models import DnsEntity  # type: ignore
    from ._models import DnsEntityProperties  # type: ignore
    from ._models import Dynamics365CheckRequirements  # type: ignore
    from ._models import Dynamics365CheckRequirementsProperties  # type: ignore
    from ._models import Dynamics365DataConnector  # type: ignore
    from ._models import Dynamics365DataConnectorDataTypes  # type: ignore
    from ._models import Dynamics365DataConnectorDataTypesDynamics365CdsActivities  # type: ignore
    from ._models import Dynamics365DataConnectorProperties  # type: ignore
    from ._models import EnrichmentDomainWhois  # type: ignore
    from ._models import EnrichmentDomainWhoisContact  # type: ignore
    from ._models import EnrichmentDomainWhoisContacts  # type: ignore
    from ._models import EnrichmentDomainWhoisDetails  # type: ignore
    from ._models import EnrichmentDomainWhoisRegistrarDetails  # type: ignore
    from ._models import EnrichmentIpGeodata  # type: ignore
    from ._models import Entity  # type: ignore
    from ._models import EntityAnalytics  # type: ignore
    from ._models import EntityCommonProperties  # type: ignore
    from ._models import EntityEdges  # type: ignore
    from ._models import EntityExpandParameters  # type: ignore
    from ._models import EntityExpandResponse  # type: ignore
    from ._models import EntityExpandResponseValue  # type: ignore
    from ._models import EntityFieldMapping  # type: ignore
    from ._models import EntityGetInsightsParameters  # type: ignore
    from ._models import EntityGetInsightsResponse  # type: ignore
    from ._models import EntityInsightItem  # type: ignore
    from ._models import EntityInsightItemQueryTimeInterval  # type: ignore
    from ._models import EntityList  # type: ignore
    from ._models import EntityMapping  # type: ignore
    from ._models import EntityQuery  # type: ignore
    from ._models import EntityQueryItem  # type: ignore
    from ._models import EntityQueryItemProperties  # type: ignore
    from ._models import EntityQueryItemPropertiesDataTypesItem  # type: ignore
    from ._models import EntityQueryList  # type: ignore
    from ._models import EntityQueryTemplate  # type: ignore
    from ._models import EntityQueryTemplateList  # type: ignore
    from ._models import EntityTimelineItem  # type: ignore
    from ._models import EntityTimelineParameters  # type: ignore
    from ._models import EntityTimelineResponse  # type: ignore
    from ._models import EventGroupingSettings  # type: ignore
    from ._models import ExpansionEntityQuery  # type: ignore
    from ._models import ExpansionResultAggregation  # type: ignore
    from ._models import ExpansionResultsMetadata  # type: ignore
    from ._models import EyesOn  # type: ignore
    from ._models import FieldMapping  # type: ignore
    from ._models import FileEntity  # type: ignore
    from ._models import FileEntityProperties  # type: ignore
    from ._models import FileHashEntity  # type: ignore
    from ._models import FileHashEntityProperties  # type: ignore
    from ._models import FusionAlertRule  # type: ignore
    from ._models import FusionAlertRuleTemplate  # type: ignore
    from ._models import FusionScenarioExclusionPattern  # type: ignore
    from ._models import FusionSourceSettings  # type: ignore
    from ._models import FusionSourceSubTypeSetting  # type: ignore
    from ._models import FusionSubTypeSeverityFilter  # type: ignore
    from ._models import FusionSubTypeSeverityFiltersItem  # type: ignore
    from ._models import FusionTemplateSourceSetting  # type: ignore
    from ._models import FusionTemplateSourceSubType  # type: ignore
    from ._models import FusionTemplateSubTypeSeverityFilter  # type: ignore
    from ._models import GeoLocation  # type: ignore
    from ._models import GetInsightsErrorKind  # type: ignore
    from ._models import GetInsightsResultsMetadata  # type: ignore
    from ._models import GetQueriesResponse  # type: ignore
    from ._models import GitHubResourceInfo  # type: ignore
    from ._models import GraphQueries  # type: ignore
    from ._models import GroupingConfiguration  # type: ignore
    from ._models import HostEntity  # type: ignore
    from ._models import HostEntityProperties  # type: ignore
    from ._models import HuntingBookmark  # type: ignore
    from ._models import HuntingBookmarkProperties  # type: ignore
    from ._models import Incident  # type: ignore
    from ._models import IncidentAdditionalData  # type: ignore
    from ._models import IncidentAlertList  # type: ignore
    from ._models import IncidentBookmarkList  # type: ignore
    from ._models import IncidentComment  # type: ignore
    from ._models import IncidentCommentList  # type: ignore
    from ._models import IncidentConfiguration  # type: ignore
    from ._models import IncidentEntitiesResponse  # type: ignore
    from ._models import IncidentEntitiesResultsMetadata  # type: ignore
    from ._models import IncidentInfo  # type: ignore
    from ._models import IncidentLabel  # type: ignore
    from ._models import IncidentList  # type: ignore
    from ._models import IncidentOwnerInfo  # type: ignore
    from ._models import IncidentPropertiesAction  # type: ignore
    from ._models import InsightQueryItem  # type: ignore
    from ._models import InsightQueryItemProperties  # type: ignore
    from ._models import InsightQueryItemPropertiesAdditionalQuery  # type: ignore
    from ._models import InsightQueryItemPropertiesDefaultTimeRange  # type: ignore
    from ._models import InsightQueryItemPropertiesReferenceTimeRange  # type: ignore
    from ._models import InsightQueryItemPropertiesTableQuery  # type: ignore
    from ._models import InsightQueryItemPropertiesTableQueryColumnsDefinitionsItem  # type: ignore
    from ._models import InsightQueryItemPropertiesTableQueryQueriesDefinitionsItem  # type: ignore
    from ._models import InsightQueryItemPropertiesTableQueryQueriesDefinitionsPropertiesItemsItem  # type: ignore
    from ._models import InsightsTableResult  # type: ignore
    from ._models import InsightsTableResultColumnsItem  # type: ignore
    from ._models import InstructionSteps  # type: ignore
    from ._models import InstructionStepsInstructionsItem  # type: ignore
    from ._models import IoTCheckRequirements  # type: ignore
    from ._models import IoTDataConnector  # type: ignore
    from ._models import IoTDataConnectorProperties  # type: ignore
    from ._models import IoTDeviceEntity  # type: ignore
    from ._models import IoTDeviceEntityProperties  # type: ignore
    from ._models import IpEntity  # type: ignore
    from ._models import IpEntityProperties  # type: ignore
    from ._models import LastDataReceivedDataType  # type: ignore
    from ._models import MailClusterEntity  # type: ignore
    from ._models import MailClusterEntityProperties  # type: ignore
    from ._models import MailMessageEntity  # type: ignore
    from ._models import MailMessageEntityProperties  # type: ignore
    from ._models import MailboxEntity  # type: ignore
    from ._models import MailboxEntityProperties  # type: ignore
    from ._models import MalwareEntity  # type: ignore
    from ._models import MalwareEntityProperties  # type: ignore
    from ._models import ManualTriggerRequestBody  # type: ignore
    from ._models import McasCheckRequirements  # type: ignore
    from ._models import McasCheckRequirementsProperties  # type: ignore
    from ._models import McasDataConnector  # type: ignore
    from ._models import McasDataConnectorDataTypes  # type: ignore
    from ._models import McasDataConnectorProperties  # type: ignore
    from ._models import MdatpCheckRequirements  # type: ignore
    from ._models import MdatpCheckRequirementsProperties  # type: ignore
    from ._models import MdatpDataConnector  # type: ignore
    from ._models import MdatpDataConnectorProperties  # type: ignore
    from ._models import MetadataAuthor  # type: ignore
    from ._models import MetadataCategories  # type: ignore
    from ._models import MetadataDependencies  # type: ignore
    from ._models import MetadataList  # type: ignore
    from ._models import MetadataModel  # type: ignore
    from ._models import MetadataPatch  # type: ignore
    from ._models import MetadataSource  # type: ignore
    from ._models import MetadataSupport  # type: ignore
    from ._models import MicrosoftSecurityIncidentCreationAlertRule  # type: ignore
    from ._models import MicrosoftSecurityIncidentCreationAlertRuleCommonProperties  # type: ignore
    from ._models import MicrosoftSecurityIncidentCreationAlertRuleProperties  # type: ignore
    from ._models import MicrosoftSecurityIncidentCreationAlertRuleTemplate  # type: ignore
    from ._models import MicrosoftSecurityIncidentCreationAlertRuleTemplateProperties  # type: ignore
    from ._models import MlBehaviorAnalyticsAlertRule  # type: ignore
    from ._models import MlBehaviorAnalyticsAlertRuleTemplate  # type: ignore
    from ._models import MlBehaviorAnalyticsAlertRuleTemplateProperties  # type: ignore
    from ._models import MstiCheckRequirements  # type: ignore
    from ._models import MstiCheckRequirementsProperties  # type: ignore
    from ._models import MstiDataConnector  # type: ignore
    from ._models import MstiDataConnectorDataTypes  # type: ignore
    from ._models import MstiDataConnectorDataTypesBingSafetyPhishingUrl  # type: ignore
    from ._models import MstiDataConnectorDataTypesMicrosoftEmergingThreatFeed  # type: ignore
    from ._models import MstiDataConnectorProperties  # type: ignore
    from ._models import MtpCheckRequirements  # type: ignore
    from ._models import MtpCheckRequirementsProperties  # type: ignore
    from ._models import MtpDataConnector  # type: ignore
    from ._models import MtpDataConnectorDataTypes  # type: ignore
    from ._models import MtpDataConnectorDataTypesIncidents  # type: ignore
    from ._models import MtpDataConnectorProperties  # type: ignore
    from ._models import NrtAlertRule  # type: ignore
    from ._models import NrtAlertRuleTemplate  # type: ignore
    from ._models import NrtAlertRuleTemplateProperties  # type: ignore
    from ._models import Office365ProjectCheckRequirements  # type: ignore
    from ._models import Office365ProjectCheckRequirementsProperties  # type: ignore
    from ._models import Office365ProjectConnectorDataTypes  # type: ignore
    from ._models import Office365ProjectConnectorDataTypesLogs  # type: ignore
    from ._models import Office365ProjectDataConnector  # type: ignore
    from ._models import Office365ProjectDataConnectorProperties  # type: ignore
    from ._models import OfficeAtpCheckRequirements  # type: ignore
    from ._models import OfficeAtpCheckRequirementsProperties  # type: ignore
    from ._models import OfficeAtpDataConnector  # type: ignore
    from ._models import OfficeAtpDataConnectorProperties  # type: ignore
    from ._models import OfficeConsent  # type: ignore
    from ._models import OfficeConsentList  # type: ignore
    from ._models import OfficeDataConnector  # type: ignore
    from ._models import OfficeDataConnectorDataTypes  # type: ignore
    from ._models import OfficeDataConnectorDataTypesExchange  # type: ignore
    from ._models import OfficeDataConnectorDataTypesSharePoint  # type: ignore
    from ._models import OfficeDataConnectorDataTypesTeams  # type: ignore
    from ._models import OfficeDataConnectorProperties  # type: ignore
    from ._models import OfficeIrmCheckRequirements  # type: ignore
    from ._models import OfficeIrmCheckRequirementsProperties  # type: ignore
    from ._models import OfficeIrmDataConnector  # type: ignore
    from ._models import OfficeIrmDataConnectorProperties  # type: ignore
    from ._models import OfficePowerBiCheckRequirements  # type: ignore
    from ._models import OfficePowerBiCheckRequirementsProperties  # type: ignore
    from ._models import OfficePowerBiConnectorDataTypes  # type: ignore
    from ._models import OfficePowerBiConnectorDataTypesLogs  # type: ignore
    from ._models import OfficePowerBiDataConnector  # type: ignore
    from ._models import OfficePowerBiDataConnectorProperties  # type: ignore
    from ._models import Operation  # type: ignore
    from ._models import OperationDisplay  # type: ignore
    from ._models import OperationsList  # type: ignore
    from ._models import Permissions  # type: ignore
    from ._models import PermissionsCustomsItem  # type: ignore
    from ._models import PermissionsResourceProviderItem  # type: ignore
    from ._models import PlaybookActionProperties  # type: ignore
    from ._models import ProcessEntity  # type: ignore
    from ._models import ProcessEntityProperties  # type: ignore
    from ._models import PropertyArrayChangedConditionProperties  # type: ignore
    from ._models import PropertyChangedConditionProperties  # type: ignore
    from ._models import PropertyConditionProperties  # type: ignore
    from ._models import QueryBasedAlertRuleTemplateProperties  # type: ignore
    from ._models import RegistryKeyEntity  # type: ignore
    from ._models import RegistryKeyEntityProperties  # type: ignore
    from ._models import RegistryValueEntity  # type: ignore
    from ._models import RegistryValueEntityProperties  # type: ignore
    from ._models import Relation  # type: ignore
    from ._models import RelationList  # type: ignore
    from ._models import Repo  # type: ignore
    from ._models import RepoList  # type: ignore
    from ._models import Repository  # type: ignore
    from ._models import RepositoryResourceInfo  # type: ignore
    from ._models import RequiredPermissions  # type: ignore
    from ._models import Resource  # type: ignore
    from ._models import ResourceProvider  # type: ignore
    from ._models import ResourceWithEtag  # type: ignore
    from ._models import SampleQueries  # type: ignore
    from ._models import ScheduledAlertRule  # type: ignore
    from ._models import ScheduledAlertRuleCommonProperties  # type: ignore
    from ._models import ScheduledAlertRuleProperties  # type: ignore
    from ._models import ScheduledAlertRuleTemplate  # type: ignore
    from ._models import SecurityAlert  # type: ignore
    from ._models import SecurityAlertProperties  # type: ignore
    from ._models import SecurityAlertPropertiesConfidenceReasonsItem  # type: ignore
    from ._models import SecurityAlertTimelineItem  # type: ignore
    from ._models import SecurityGroupEntity  # type: ignore
    from ._models import SecurityGroupEntityProperties  # type: ignore
    from ._models import SecurityMlAnalyticsSetting  # type: ignore
    from ._models import SecurityMlAnalyticsSettingsDataSource  # type: ignore
    from ._models import SecurityMlAnalyticsSettingsList  # type: ignore
    from ._models import SentinelOnboardingState  # type: ignore
    from ._models import SentinelOnboardingStatesList  # type: ignore
    from ._models import SettingList  # type: ignore
    from ._models import Settings  # type: ignore
    from ._models import SourceControl  # type: ignore
    from ._models import SourceControlList  # type: ignore
    from ._models import SubmissionMailEntity  # type: ignore
    from ._models import SubmissionMailEntityProperties  # type: ignore
    from ._models import SystemData  # type: ignore
    from ._models import TeamInformation  # type: ignore
    from ._models import TeamProperties  # type: ignore
    from ._models import ThreatIntelligence  # type: ignore
    from ._models import ThreatIntelligenceAlertRule  # type: ignore
    from ._models import ThreatIntelligenceAlertRuleTemplate  # type: ignore
    from ._models import ThreatIntelligenceAlertRuleTemplateProperties  # type: ignore
    from ._models import ThreatIntelligenceAppendTags  # type: ignore
    from ._models import ThreatIntelligenceExternalReference  # type: ignore
    from ._models import ThreatIntelligenceFilteringCriteria  # type: ignore
    from ._models import ThreatIntelligenceGranularMarkingModel  # type: ignore
    from ._models import ThreatIntelligenceIndicatorModel  # type: ignore
    from ._models import ThreatIntelligenceIndicatorProperties  # type: ignore
    from ._models import ThreatIntelligenceInformation  # type: ignore
    from ._models import ThreatIntelligenceInformationList  # type: ignore
    from ._models import ThreatIntelligenceKillChainPhase  # type: ignore
    from ._models import ThreatIntelligenceMetric  # type: ignore
    from ._models import ThreatIntelligenceMetricEntity  # type: ignore
    from ._models import ThreatIntelligenceMetrics  # type: ignore
    from ._models import ThreatIntelligenceMetricsList  # type: ignore
    from ._models import ThreatIntelligenceParsedPattern  # type: ignore
    from ._models import ThreatIntelligenceParsedPatternTypeValue  # type: ignore
    from ._models import ThreatIntelligenceSortingCriteria  # type: ignore
    from ._models import TiCheckRequirements  # type: ignore
    from ._models import TiCheckRequirementsProperties  # type: ignore
    from ._models import TiDataConnector  # type: ignore
    from ._models import TiDataConnectorDataTypes  # type: ignore
    from ._models import TiDataConnectorDataTypesIndicators  # type: ignore
    from ._models import TiDataConnectorProperties  # type: ignore
    from ._models import TiTaxiiCheckRequirements  # type: ignore
    from ._models import TiTaxiiCheckRequirementsProperties  # type: ignore
    from ._models import TiTaxiiDataConnector  # type: ignore
    from ._models import TiTaxiiDataConnectorDataTypes  # type: ignore
    from ._models import TiTaxiiDataConnectorDataTypesTaxiiClient  # type: ignore
    from ._models import TiTaxiiDataConnectorProperties  # type: ignore
    from ._models import TimelineAggregation  # type: ignore
    from ._models import TimelineError  # type: ignore
    from ._models import TimelineResultsMetadata  # type: ignore
    from ._models import Ueba  # type: ignore
    from ._models import UrlEntity  # type: ignore
    from ._models import UrlEntityProperties  # type: ignore
    from ._models import UserInfo  # type: ignore
    from ._models import Watchlist  # type: ignore
    from ._models import WatchlistItem  # type: ignore
    from ._models import WatchlistItemList  # type: ignore
    from ._models import WatchlistList  # type: ignore
    from ._models import Webhook  # type: ignore

from ._security_insights_enums import (
    ActionType,
    AlertDetail,
    AlertRuleKind,
    AlertSeverity,
    AlertStatus,
    AntispamMailDirection,
    AttackTactic,
    AutomationRulePropertyArrayChangedConditionSupportedArrayType,
    AutomationRulePropertyArrayChangedConditionSupportedChangeType,
    AutomationRulePropertyChangedConditionSupportedChangedType,
    AutomationRulePropertyChangedConditionSupportedPropertyType,
    AutomationRulePropertyConditionSupportedOperator,
    AutomationRulePropertyConditionSupportedProperty,
    ConditionType,
    ConfidenceLevel,
    ConfidenceScoreStatus,
    ConnectAuthKind,
    ConnectivityType,
    ContentType,
    CreatedByType,
    CustomEntityQueryKind,
    DataConnectorAuthorizationState,
    DataConnectorKind,
    DataConnectorLicenseState,
    DataTypeState,
    DeliveryAction,
    DeliveryLocation,
    DeploymentFetchStatus,
    DeploymentResult,
    DeploymentState,
    ElevationToken,
    EntityItemQueryKind,
    EntityKind,
    EntityMappingType,
    EntityProviders,
    EntityQueryKind,
    EntityQueryTemplateKind,
    EntityTimelineKind,
    EntityType,
    Enum13,
    EventGroupingAggregationKind,
    FileHashAlgorithm,
    GetInsightsError,
    IncidentClassification,
    IncidentClassificationReason,
    IncidentLabelType,
    IncidentSeverity,
    IncidentStatus,
    KillChainIntent,
    Kind,
    MatchingMethod,
    MicrosoftSecurityProductName,
    Operator,
    OsFamily,
    OutputType,
    OwnerType,
    PermissionProviderScope,
    PollingFrequency,
    ProviderName,
    RegistryHive,
    RegistryValueKind,
    RepoType,
    SecurityMlAnalyticsSettingsKind,
    SettingKind,
    SettingType,
    SettingsStatus,
    SourceKind,
    SourceType,
    SupportTier,
    TemplateStatus,
    ThreatIntelligenceResourceKindEnum,
    ThreatIntelligenceSortingCriteriaEnum,
    TriggerOperator,
    TriggersOn,
    TriggersWhen,
    UebaDataSources,
    Version,
)

__all__ = [
    'AadCheckRequirements',
    'AadCheckRequirementsProperties',
    'AadDataConnector',
    'AadDataConnectorProperties',
    'AatpCheckRequirements',
    'AatpCheckRequirementsProperties',
    'AatpDataConnector',
    'AatpDataConnectorProperties',
    'AccountEntity',
    'AccountEntityProperties',
    'ActionPropertiesBase',
    'ActionRequest',
    'ActionRequestProperties',
    'ActionResponse',
    'ActionResponseProperties',
    'ActionsList',
    'ActivityCustomEntityQuery',
    'ActivityEntityQueriesPropertiesQueryDefinitions',
    'ActivityEntityQuery',
    'ActivityEntityQueryTemplate',
    'ActivityEntityQueryTemplatePropertiesQueryDefinitions',
    'ActivityTimelineItem',
    'AlertDetailsOverride',
    'AlertRule',
    'AlertRuleTemplate',
    'AlertRuleTemplateDataSource',
    'AlertRuleTemplatePropertiesBase',
    'AlertRuleTemplateWithMitreProperties',
    'AlertRuleTemplatesList',
    'AlertRulesList',
    'AlertsDataTypeOfDataConnector',
    'Anomalies',
    'AnomalySecurityMlAnalyticsSettings',
    'AnomalyTimelineItem',
    'AscCheckRequirements',
    'AscDataConnector',
    'AscDataConnectorProperties',
    'AutomationRule',
    'AutomationRuleAction',
    'AutomationRuleCondition',
    'AutomationRuleModifyPropertiesAction',
    'AutomationRulePropertyArrayChangedValuesCondition',
    'AutomationRulePropertyValuesChangedCondition',
    'AutomationRulePropertyValuesCondition',
    'AutomationRuleRunPlaybookAction',
    'AutomationRuleTriggeringLogic',
    'AutomationRulesList',
    'Availability',
    'AwsCloudTrailCheckRequirements',
    'AwsCloudTrailDataConnector',
    'AwsCloudTrailDataConnectorDataTypes',
    'AwsCloudTrailDataConnectorDataTypesLogs',
    'AwsS3CheckRequirements',
    'AwsS3DataConnector',
    'AwsS3DataConnectorDataTypes',
    'AwsS3DataConnectorDataTypesLogs',
    'AzureDevOpsResourceInfo',
    'AzureResourceEntity',
    'AzureResourceEntityProperties',
    'Bookmark',
    'BookmarkEntityMappings',
    'BookmarkExpandParameters',
    'BookmarkExpandResponse',
    'BookmarkExpandResponseValue',
    'BookmarkList',
    'BookmarkTimelineItem',
    'ClientInfo',
    'CloudApplicationEntity',
    'CloudApplicationEntityProperties',
    'CloudErrorBody',
    'CodelessApiPollingDataConnector',
    'CodelessConnectorPollingAuthProperties',
    'CodelessConnectorPollingConfigProperties',
    'CodelessConnectorPollingPagingProperties',
    'CodelessConnectorPollingRequestProperties',
    'CodelessConnectorPollingResponseProperties',
    'CodelessUiConnectorConfigProperties',
    'CodelessUiConnectorConfigPropertiesConnectivityCriteriaItem',
    'CodelessUiConnectorConfigPropertiesDataTypesItem',
    'CodelessUiConnectorConfigPropertiesGraphQueriesItem',
    'CodelessUiConnectorConfigPropertiesInstructionStepsItem',
    'CodelessUiConnectorConfigPropertiesSampleQueriesItem',
    'CodelessUiDataConnector',
    'ConnectedEntity',
    'ConnectivityCriteria',
    'ConnectorInstructionModelBase',
    'ContentPathMap',
    'CustomEntityQuery',
    'Customs',
    'CustomsPermission',
    'DataConnector',
    'DataConnectorConnectBody',
    'DataConnectorDataTypeCommon',
    'DataConnectorList',
    'DataConnectorRequirementsState',
    'DataConnectorTenantId',
    'DataConnectorWithAlertsProperties',
    'DataConnectorsCheckRequirements',
    'DataTypeDefinitions',
    'Deployment',
    'DeploymentInfo',
    'DnsEntity',
    'DnsEntityProperties',
    'Dynamics365CheckRequirements',
    'Dynamics365CheckRequirementsProperties',
    'Dynamics365DataConnector',
    'Dynamics365DataConnectorDataTypes',
    'Dynamics365DataConnectorDataTypesDynamics365CdsActivities',
    'Dynamics365DataConnectorProperties',
    'EnrichmentDomainWhois',
    'EnrichmentDomainWhoisContact',
    'EnrichmentDomainWhoisContacts',
    'EnrichmentDomainWhoisDetails',
    'EnrichmentDomainWhoisRegistrarDetails',
    'EnrichmentIpGeodata',
    'Entity',
    'EntityAnalytics',
    'EntityCommonProperties',
    'EntityEdges',
    'EntityExpandParameters',
    'EntityExpandResponse',
    'EntityExpandResponseValue',
    'EntityFieldMapping',
    'EntityGetInsightsParameters',
    'EntityGetInsightsResponse',
    'EntityInsightItem',
    'EntityInsightItemQueryTimeInterval',
    'EntityList',
    'EntityMapping',
    'EntityQuery',
    'EntityQueryItem',
    'EntityQueryItemProperties',
    'EntityQueryItemPropertiesDataTypesItem',
    'EntityQueryList',
    'EntityQueryTemplate',
    'EntityQueryTemplateList',
    'EntityTimelineItem',
    'EntityTimelineParameters',
    'EntityTimelineResponse',
    'EventGroupingSettings',
    'ExpansionEntityQuery',
    'ExpansionResultAggregation',
    'ExpansionResultsMetadata',
    'EyesOn',
    'FieldMapping',
    'FileEntity',
    'FileEntityProperties',
    'FileHashEntity',
    'FileHashEntityProperties',
    'FusionAlertRule',
    'FusionAlertRuleTemplate',
    'FusionScenarioExclusionPattern',
    'FusionSourceSettings',
    'FusionSourceSubTypeSetting',
    'FusionSubTypeSeverityFilter',
    'FusionSubTypeSeverityFiltersItem',
    'FusionTemplateSourceSetting',
    'FusionTemplateSourceSubType',
    'FusionTemplateSubTypeSeverityFilter',
    'GeoLocation',
    'GetInsightsErrorKind',
    'GetInsightsResultsMetadata',
    'GetQueriesResponse',
    'GitHubResourceInfo',
    'GraphQueries',
    'GroupingConfiguration',
    'HostEntity',
    'HostEntityProperties',
    'HuntingBookmark',
    'HuntingBookmarkProperties',
    'Incident',
    'IncidentAdditionalData',
    'IncidentAlertList',
    'IncidentBookmarkList',
    'IncidentComment',
    'IncidentCommentList',
    'IncidentConfiguration',
    'IncidentEntitiesResponse',
    'IncidentEntitiesResultsMetadata',
    'IncidentInfo',
    'IncidentLabel',
    'IncidentList',
    'IncidentOwnerInfo',
    'IncidentPropertiesAction',
    'InsightQueryItem',
    'InsightQueryItemProperties',
    'InsightQueryItemPropertiesAdditionalQuery',
    'InsightQueryItemPropertiesDefaultTimeRange',
    'InsightQueryItemPropertiesReferenceTimeRange',
    'InsightQueryItemPropertiesTableQuery',
    'InsightQueryItemPropertiesTableQueryColumnsDefinitionsItem',
    'InsightQueryItemPropertiesTableQueryQueriesDefinitionsItem',
    'InsightQueryItemPropertiesTableQueryQueriesDefinitionsPropertiesItemsItem',
    'InsightsTableResult',
    'InsightsTableResultColumnsItem',
    'InstructionSteps',
    'InstructionStepsInstructionsItem',
    'IoTCheckRequirements',
    'IoTDataConnector',
    'IoTDataConnectorProperties',
    'IoTDeviceEntity',
    'IoTDeviceEntityProperties',
    'IpEntity',
    'IpEntityProperties',
    'LastDataReceivedDataType',
    'MailClusterEntity',
    'MailClusterEntityProperties',
    'MailMessageEntity',
    'MailMessageEntityProperties',
    'MailboxEntity',
    'MailboxEntityProperties',
    'MalwareEntity',
    'MalwareEntityProperties',
    'ManualTriggerRequestBody',
    'McasCheckRequirements',
    'McasCheckRequirementsProperties',
    'McasDataConnector',
    'McasDataConnectorDataTypes',
    'McasDataConnectorProperties',
    'MdatpCheckRequirements',
    'MdatpCheckRequirementsProperties',
    'MdatpDataConnector',
    'MdatpDataConnectorProperties',
    'MetadataAuthor',
    'MetadataCategories',
    'MetadataDependencies',
    'MetadataList',
    'MetadataModel',
    'MetadataPatch',
    'MetadataSource',
    'MetadataSupport',
    'MicrosoftSecurityIncidentCreationAlertRule',
    'MicrosoftSecurityIncidentCreationAlertRuleCommonProperties',
    'MicrosoftSecurityIncidentCreationAlertRuleProperties',
    'MicrosoftSecurityIncidentCreationAlertRuleTemplate',
    'MicrosoftSecurityIncidentCreationAlertRuleTemplateProperties',
    'MlBehaviorAnalyticsAlertRule',
    'MlBehaviorAnalyticsAlertRuleTemplate',
    'MlBehaviorAnalyticsAlertRuleTemplateProperties',
    'MstiCheckRequirements',
    'MstiCheckRequirementsProperties',
    'MstiDataConnector',
    'MstiDataConnectorDataTypes',
    'MstiDataConnectorDataTypesBingSafetyPhishingUrl',
    'MstiDataConnectorDataTypesMicrosoftEmergingThreatFeed',
    'MstiDataConnectorProperties',
    'MtpCheckRequirements',
    'MtpCheckRequirementsProperties',
    'MtpDataConnector',
    'MtpDataConnectorDataTypes',
    'MtpDataConnectorDataTypesIncidents',
    'MtpDataConnectorProperties',
    'NrtAlertRule',
    'NrtAlertRuleTemplate',
    'NrtAlertRuleTemplateProperties',
    'Office365ProjectCheckRequirements',
    'Office365ProjectCheckRequirementsProperties',
    'Office365ProjectConnectorDataTypes',
    'Office365ProjectConnectorDataTypesLogs',
    'Office365ProjectDataConnector',
    'Office365ProjectDataConnectorProperties',
    'OfficeAtpCheckRequirements',
    'OfficeAtpCheckRequirementsProperties',
    'OfficeAtpDataConnector',
    'OfficeAtpDataConnectorProperties',
    'OfficeConsent',
    'OfficeConsentList',
    'OfficeDataConnector',
    'OfficeDataConnectorDataTypes',
    'OfficeDataConnectorDataTypesExchange',
    'OfficeDataConnectorDataTypesSharePoint',
    'OfficeDataConnectorDataTypesTeams',
    'OfficeDataConnectorProperties',
    'OfficeIrmCheckRequirements',
    'OfficeIrmCheckRequirementsProperties',
    'OfficeIrmDataConnector',
    'OfficeIrmDataConnectorProperties',
    'OfficePowerBiCheckRequirements',
    'OfficePowerBiCheckRequirementsProperties',
    'OfficePowerBiConnectorDataTypes',
    'OfficePowerBiConnectorDataTypesLogs',
    'OfficePowerBiDataConnector',
    'OfficePowerBiDataConnectorProperties',
    'Operation',
    'OperationDisplay',
    'OperationsList',
    'Permissions',
    'PermissionsCustomsItem',
    'PermissionsResourceProviderItem',
    'PlaybookActionProperties',
    'ProcessEntity',
    'ProcessEntityProperties',
    'PropertyArrayChangedConditionProperties',
    'PropertyChangedConditionProperties',
    'PropertyConditionProperties',
    'QueryBasedAlertRuleTemplateProperties',
    'RegistryKeyEntity',
    'RegistryKeyEntityProperties',
    'RegistryValueEntity',
    'RegistryValueEntityProperties',
    'Relation',
    'RelationList',
    'Repo',
    'RepoList',
    'Repository',
    'RepositoryResourceInfo',
    'RequiredPermissions',
    'Resource',
    'ResourceProvider',
    'ResourceWithEtag',
    'SampleQueries',
    'ScheduledAlertRule',
    'ScheduledAlertRuleCommonProperties',
    'ScheduledAlertRuleProperties',
    'ScheduledAlertRuleTemplate',
    'SecurityAlert',
    'SecurityAlertProperties',
    'SecurityAlertPropertiesConfidenceReasonsItem',
    'SecurityAlertTimelineItem',
    'SecurityGroupEntity',
    'SecurityGroupEntityProperties',
    'SecurityMlAnalyticsSetting',
    'SecurityMlAnalyticsSettingsDataSource',
    'SecurityMlAnalyticsSettingsList',
    'SentinelOnboardingState',
    'SentinelOnboardingStatesList',
    'SettingList',
    'Settings',
    'SourceControl',
    'SourceControlList',
    'SubmissionMailEntity',
    'SubmissionMailEntityProperties',
    'SystemData',
    'TeamInformation',
    'TeamProperties',
    'ThreatIntelligence',
    'ThreatIntelligenceAlertRule',
    'ThreatIntelligenceAlertRuleTemplate',
    'ThreatIntelligenceAlertRuleTemplateProperties',
    'ThreatIntelligenceAppendTags',
    'ThreatIntelligenceExternalReference',
    'ThreatIntelligenceFilteringCriteria',
    'ThreatIntelligenceGranularMarkingModel',
    'ThreatIntelligenceIndicatorModel',
    'ThreatIntelligenceIndicatorProperties',
    'ThreatIntelligenceInformation',
    'ThreatIntelligenceInformationList',
    'ThreatIntelligenceKillChainPhase',
    'ThreatIntelligenceMetric',
    'ThreatIntelligenceMetricEntity',
    'ThreatIntelligenceMetrics',
    'ThreatIntelligenceMetricsList',
    'ThreatIntelligenceParsedPattern',
    'ThreatIntelligenceParsedPatternTypeValue',
    'ThreatIntelligenceSortingCriteria',
    'TiCheckRequirements',
    'TiCheckRequirementsProperties',
    'TiDataConnector',
    'TiDataConnectorDataTypes',
    'TiDataConnectorDataTypesIndicators',
    'TiDataConnectorProperties',
    'TiTaxiiCheckRequirements',
    'TiTaxiiCheckRequirementsProperties',
    'TiTaxiiDataConnector',
    'TiTaxiiDataConnectorDataTypes',
    'TiTaxiiDataConnectorDataTypesTaxiiClient',
    'TiTaxiiDataConnectorProperties',
    'TimelineAggregation',
    'TimelineError',
    'TimelineResultsMetadata',
    'Ueba',
    'UrlEntity',
    'UrlEntityProperties',
    'UserInfo',
    'Watchlist',
    'WatchlistItem',
    'WatchlistItemList',
    'WatchlistList',
    'Webhook',
    'ActionType',
    'AlertDetail',
    'AlertRuleKind',
    'AlertSeverity',
    'AlertStatus',
    'AntispamMailDirection',
    'AttackTactic',
    'AutomationRulePropertyArrayChangedConditionSupportedArrayType',
    'AutomationRulePropertyArrayChangedConditionSupportedChangeType',
    'AutomationRulePropertyChangedConditionSupportedChangedType',
    'AutomationRulePropertyChangedConditionSupportedPropertyType',
    'AutomationRulePropertyConditionSupportedOperator',
    'AutomationRulePropertyConditionSupportedProperty',
    'ConditionType',
    'ConfidenceLevel',
    'ConfidenceScoreStatus',
    'ConnectAuthKind',
    'ConnectivityType',
    'ContentType',
    'CreatedByType',
    'CustomEntityQueryKind',
    'DataConnectorAuthorizationState',
    'DataConnectorKind',
    'DataConnectorLicenseState',
    'DataTypeState',
    'DeliveryAction',
    'DeliveryLocation',
    'DeploymentFetchStatus',
    'DeploymentResult',
    'DeploymentState',
    'ElevationToken',
    'EntityItemQueryKind',
    'EntityKind',
    'EntityMappingType',
    'EntityProviders',
    'EntityQueryKind',
    'EntityQueryTemplateKind',
    'EntityTimelineKind',
    'EntityType',
    'Enum13',
    'EventGroupingAggregationKind',
    'FileHashAlgorithm',
    'GetInsightsError',
    'IncidentClassification',
    'IncidentClassificationReason',
    'IncidentLabelType',
    'IncidentSeverity',
    'IncidentStatus',
    'KillChainIntent',
    'Kind',
    'MatchingMethod',
    'MicrosoftSecurityProductName',
    'Operator',
    'OsFamily',
    'OutputType',
    'OwnerType',
    'PermissionProviderScope',
    'PollingFrequency',
    'ProviderName',
    'RegistryHive',
    'RegistryValueKind',
    'RepoType',
    'SecurityMlAnalyticsSettingsKind',
    'SettingKind',
    'SettingType',
    'SettingsStatus',
    'SourceKind',
    'SourceType',
    'SupportTier',
    'TemplateStatus',
    'ThreatIntelligenceResourceKindEnum',
    'ThreatIntelligenceSortingCriteriaEnum',
    'TriggerOperator',
    'TriggersOn',
    'TriggersWhen',
    'UebaDataSources',
    'Version',
]
