# --------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for
# license information.
#
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

import os
from azure.cli.testsdk import ScenarioTest
from azure.cli.testsdk import ResourceGroupPreparer
from .example_steps import step_action_create
from .example_steps import step_action_list
from .example_steps import step_action_show
from .example_steps import step_automation_rule_create
from .example_steps import step_action_delete
from .example_steps import step_alert_rule_create
from .example_steps import step_alert_rule_create2
from .example_steps import step_alert_rule_create3
from .example_steps import step_alert_rule_create4
from .example_steps import step_alert_rule_create5
from .example_steps import step_alert_rule_show
from .example_steps import step_alert_rule_show2
from .example_steps import step_alert_rule_show3
from .example_steps import step_alert_rule_list
from .example_steps import step_alert_rule_show4
from .example_steps import step_alert_rule_delete
from .example_steps import step_alert_rule_template_show
from .example_steps import step_alert_rule_template_list
from .example_steps import step_automation_rule_show
from .example_steps import step_automation_rule_list
from .example_steps import step_automation_rule_delete
from .example_steps import step_bookmark_relation_create
from .example_steps import step_bookmark_relation_show
from .example_steps import step_bookmark_relation_list
from .example_steps import step_bookmark_relation_delete
from .example_steps import step_bookmark_create
from .example_steps import step_bookmark_show
from .example_steps import step_bookmark_list
from .example_steps import step_bookmark_expand
from .example_steps import step_bookmark_delete
from .example_steps import step_data_connector_create
from .example_steps import step_data_connector_create2
from .example_steps import step_data_connector_create3
from .example_steps import step_data_connector_create4
from .example_steps import step_data_connector_create5
from .example_steps import step_data_connector_create6
from .example_steps import step_data_connector_create7
from .example_steps import step_data_connector_create8
from .example_steps import step_data_connector_show
from .example_steps import step_data_connector_show2
from .example_steps import step_data_connector_show3
from .example_steps import step_data_connector_show4
from .example_steps import step_data_connector_show5
from .example_steps import step_data_connector_show6
from .example_steps import step_data_connector_show7
from .example_steps import step_data_connector_show8
from .example_steps import step_data_connector_show9
from .example_steps import step_data_connector_show10
from .example_steps import step_data_connector_show11
from .example_steps import step_data_connector_list
from .example_steps import step_data_connector_show12
from .example_steps import step_data_connector_show13
from .example_steps import step_data_connector_show14
from .example_steps import step_data_connector_show15
from .example_steps import step_data_connector_show16
from .example_steps import step_data_connector_show17
from .example_steps import step_data_connector_show18
from .example_steps import step_data_connector_show19
from .example_steps import step_data_connector_show20
from .example_steps import step_data_connector_connect
from .example_steps import step_data_connector_connect2
from .example_steps import step_data_connector_disconnect
from .example_steps import step_data_connector_delete
from .example_steps import step_data_connector_delete2
from .example_steps import step_data_connector_delete3
from .example_steps import step_data_connector_delete4
from .example_steps import step_data_connector_delete5
from .example_steps import step_data_connector_check_requirement
from .example_steps import step_data_connector_check_requirement2
from .example_steps import step_data_connector_check_requirement3
from .example_steps import step_domain_whois_show
from .example_steps import step_entity_show
from .example_steps import step_entity_show2
from .example_steps import step_entity_show3
from .example_steps import step_entity_show4
from .example_steps import step_entity_show5
from .example_steps import step_entity_show6
from .example_steps import step_entity_show7
from .example_steps import step_entity_show8
from .example_steps import step_entity_show9
from .example_steps import step_entity_show10
from .example_steps import step_entity_show11
from .example_steps import step_entity_show12
from .example_steps import step_entity_show13
from .example_steps import step_entity_show14
from .example_steps import step_entity_show15
from .example_steps import step_entity_show16
from .example_steps import step_entity_list
from .example_steps import step_entity_show17
from .example_steps import step_entity_show18
from .example_steps import step_entity_show19
from .example_steps import step_entity_show20
from .example_steps import step_entity_list_insight
from .example_steps import step_entity_expand
from .example_steps import step_entity_list_timeline
from .example_steps import step_entity_relation_list
from .example_steps import step_entity_query_create
from .example_steps import step_entity_query_list
from .example_steps import step_entity_query_show
from .example_steps import step_entity_query_show2
from .example_steps import step_entity_query_delete
from .example_steps import step_entity_template_list
from .example_steps import step_entity_template_show
from .example_steps import step_entity_relation_show
from .example_steps import step_incident_comment_create
from .example_steps import step_incident_comment_list
from .example_steps import step_incident_comment_show
from .example_steps import step_incident_comment_delete
from .example_steps import step_incident_relation_create
from .example_steps import step_incident_relation_list
from .example_steps import step_incident_relation_show
from .example_steps import step_incident_relation_delete
from .example_steps import step_incident_create
from .example_steps import step_incident_list
from .example_steps import step_incident_show
from .example_steps import step_incident_create_team
from .example_steps import step_incident_list_alert
from .example_steps import step_incident_list_bookmark
from .example_steps import step_incident_list_entity
from .example_steps import step_incident_run_playbook
from .example_steps import step_incident_delete
from .example_steps import step_ip_geodata_show
from .example_steps import step_metadata_create
from .example_steps import step_metadata_create2
from .example_steps import step_metadata_list
from .example_steps import step_metadata_list2
from .example_steps import step_metadata_show
from .example_steps import step_metadata_update
from .example_steps import step_metadata_delete
from .example_steps import step_office_consent_list
from .example_steps import step_office_consent_show
from .example_steps import step_office_consent_delete
from .example_steps import step_product_setting_list
from .example_steps import step_product_setting_show
from .example_steps import step_product_setting_delete
from .example_steps import step_analytic_setting_create
from .example_steps import step_analytic_setting_show
from .example_steps import step_analytic_setting_list
from .example_steps import step_analytic_setting_delete
from .example_steps import step_onboarding_state_create
from .example_steps import step_onboarding_state_list
from .example_steps import step_onboarding_state_show
from .example_steps import step_onboarding_state_delete
from .example_steps import step_source_control_list_repository
from .example_steps import step_source_control_create
from .example_steps import step_source_control_show
from .example_steps import step_source_control_list
from .example_steps import step_source_control_delete
from .example_steps import step_threat_indicator_update
from .example_steps import step_threat_indicator_show
from .example_steps import step_threat_indicator_append_tag
from .example_steps import step_threat_indicator_create
from .example_steps import step_threat_indicator_query
from .example_steps import step_threat_indicator_replace_tag
from .example_steps import step_threat_indicator_delete
from .example_steps import step_threat_indicator_metric_list
from .example_steps import step_threat_indicator_list
from .example_steps import step_watchlist_item_create
from .example_steps import step_watchlist_item_show
from .example_steps import step_watchlist_item_list
from .example_steps import step_watchlist_item_delete
from .example_steps import step_watchlist_create
from .example_steps import step_watchlist_create2
from .example_steps import step_watchlist_show
from .example_steps import step_watchlist_list
from .example_steps import step_watchlist_delete
from .. import (
    try_manual,
    raise_if,
    calc_coverage
)


TEST_DIR = os.path.abspath(os.path.join(os.path.abspath(__file__), '..'))


# Env setup_scenario
@try_manual
def setup_scenario(test):
    pass


# Env cleanup_scenario
@try_manual
def cleanup_scenario(test):
    pass


# Testcase: Scenario
@try_manual
def call_scenario(test):
    setup_scenario(test)
    step_action_create(test, checks=[])
    step_action_list(test, checks=[])
    step_action_show(test, checks=[])
    step_automation_rule_create(test, checks=[])
    step_action_delete(test, checks=[])
    step_alert_rule_create(test, checks=[])
    step_alert_rule_create2(test, checks=[])
    step_alert_rule_create3(test, checks=[])
    step_alert_rule_create4(test, checks=[])
    step_alert_rule_create5(test, checks=[])
    step_alert_rule_show(test, checks=[])
    step_alert_rule_show2(test, checks=[])
    step_alert_rule_show3(test, checks=[])
    step_alert_rule_list(test, checks=[])
    step_alert_rule_show4(test, checks=[])
    step_alert_rule_delete(test, checks=[])
    step_alert_rule_template_show(test, checks=[])
    step_alert_rule_template_list(test, checks=[])
    step_automation_rule_show(test, checks=[])
    step_automation_rule_list(test, checks=[])
    step_automation_rule_delete(test, checks=[])
    step_bookmark_relation_create(test, checks=[])
    step_bookmark_relation_show(test, checks=[])
    step_bookmark_relation_list(test, checks=[])
    step_bookmark_relation_delete(test, checks=[])
    step_bookmark_create(test, checks=[])
    step_bookmark_show(test, checks=[])
    step_bookmark_list(test, checks=[])
    step_bookmark_expand(test, checks=[])
    step_bookmark_delete(test, checks=[])
    step_data_connector_create(test, checks=[])
    step_data_connector_create2(test, checks=[])
    step_data_connector_create3(test, checks=[])
    step_data_connector_create4(test, checks=[])
    step_data_connector_create5(test, checks=[])
    step_data_connector_create6(test, checks=[])
    step_data_connector_create7(test, checks=[])
    step_data_connector_create8(test, checks=[])
    step_data_connector_show(test, checks=[])
    step_data_connector_show2(test, checks=[])
    step_data_connector_show3(test, checks=[])
    step_data_connector_show4(test, checks=[])
    step_data_connector_show5(test, checks=[])
    step_data_connector_show6(test, checks=[])
    step_data_connector_show7(test, checks=[])
    step_data_connector_show8(test, checks=[])
    step_data_connector_show9(test, checks=[])
    step_data_connector_show10(test, checks=[])
    step_data_connector_show11(test, checks=[])
    step_data_connector_list(test, checks=[])
    step_data_connector_show12(test, checks=[])
    step_data_connector_show13(test, checks=[])
    step_data_connector_show14(test, checks=[])
    step_data_connector_show15(test, checks=[])
    step_data_connector_show16(test, checks=[])
    step_data_connector_show17(test, checks=[])
    step_data_connector_show18(test, checks=[])
    step_data_connector_show19(test, checks=[])
    step_data_connector_show20(test, checks=[])
    step_data_connector_connect(test, checks=[])
    step_data_connector_connect2(test, checks=[])
    step_data_connector_disconnect(test, checks=[])
    step_data_connector_delete(test, checks=[])
    step_data_connector_delete2(test, checks=[])
    step_data_connector_delete3(test, checks=[])
    step_data_connector_delete4(test, checks=[])
    step_data_connector_delete5(test, checks=[])
    step_data_connector_check_requirement(test, checks=[])
    step_data_connector_check_requirement2(test, checks=[])
    step_data_connector_check_requirement3(test, checks=[])
    step_domain_whois_show(test, checks=[])
    step_entity_show(test, checks=[])
    step_entity_show2(test, checks=[])
    step_entity_show3(test, checks=[])
    step_entity_show4(test, checks=[])
    step_entity_show5(test, checks=[])
    step_entity_show6(test, checks=[])
    step_entity_show7(test, checks=[])
    step_entity_show8(test, checks=[])
    step_entity_show9(test, checks=[])
    step_entity_show10(test, checks=[])
    step_entity_show11(test, checks=[])
    step_entity_show12(test, checks=[])
    step_entity_show13(test, checks=[])
    step_entity_show14(test, checks=[])
    step_entity_show15(test, checks=[])
    step_entity_show16(test, checks=[])
    step_entity_list(test, checks=[])
    step_entity_show17(test, checks=[])
    step_entity_show18(test, checks=[])
    step_entity_show19(test, checks=[])
    step_entity_show20(test, checks=[])
    step_entity_list_insight(test, checks=[])
    step_entity_expand(test, checks=[])
    step_entity_list_timeline(test, checks=[])
    step_entity_relation_list(test, checks=[])
    step_entity_query_create(test, checks=[])
    step_entity_query_list(test, checks=[])
    step_entity_query_show(test, checks=[])
    step_entity_query_show2(test, checks=[])
    step_entity_query_delete(test, checks=[])
    step_entity_template_list(test, checks=[])
    step_entity_template_show(test, checks=[])
    step_entity_relation_show(test, checks=[])
    step_incident_comment_create(test, checks=[])
    step_incident_comment_list(test, checks=[])
    step_incident_comment_show(test, checks=[])
    step_incident_comment_delete(test, checks=[])
    step_incident_relation_create(test, checks=[])
    step_incident_relation_list(test, checks=[])
    step_incident_relation_show(test, checks=[])
    step_incident_relation_delete(test, checks=[])
    step_incident_create(test, checks=[])
    step_incident_list(test, checks=[])
    step_incident_show(test, checks=[])
    step_incident_create_team(test, checks=[])
    step_incident_list_alert(test, checks=[])
    step_incident_list_bookmark(test, checks=[])
    step_incident_list_entity(test, checks=[])
    step_incident_run_playbook(test, checks=[])
    step_incident_delete(test, checks=[])
    step_ip_geodata_show(test, checks=[])
    step_metadata_create(test, checks=[
        test.check("author.name", "User Name", case_sensitive=False),
        test.check("author.email", "email@microsoft.com", case_sensitive=False),
        test.check("contentId", "c00ee137-7475-47c8-9cce-ec6f0f1bedd0", case_sensitive=False),
        test.check("contentSchemaVersion", "2.0", case_sensitive=False),
        test.check("customVersion", "1.0", case_sensitive=False),
        test.check("firstPublishDate", "2021-05-18", case_sensitive=False),
        test.check("kind", "AnalyticsRule", case_sensitive=False),
        test.check("lastPublishDate", "2021-05-18", case_sensitive=False),
        test.check("parentId", "/subscriptions/{subscription_id}/resourceGroups/{rg}/providers/Microsoft.OperationalIns"
                   "ights/workspaces/myWorkspace/providers/Microsoft.SecurityInsights/alertRules/{myAlertRule}",
                   case_sensitive=False),
        test.check("source.name", "Contoso Solution 1.0", case_sensitive=False),
        test.check("source.kind", "Solution", case_sensitive=False),
        test.check("source.sourceId", "b688a130-76f4-4a07-bf57-762222a3cadf", case_sensitive=False),
        test.check("support.name", "Microsoft", case_sensitive=False),
        test.check("support.email", "support@microsoft.com", case_sensitive=False),
        test.check("support.link", "https://support.microsoft.com/", case_sensitive=False),
        test.check("support.tier", "Partner", case_sensitive=False),
        test.check("version", "1.0.0.0", case_sensitive=False),
        test.check("name", "{myMetadata}", case_sensitive=False),
    ])
    step_metadata_create2(test, checks=[
        test.check("kind", "AnalyticsRule", case_sensitive=False),
        test.check("parentId", "/subscriptions/{subscription_id}/resourceGroups/{rg}/providers/Microsoft.OperationalIns"
                   "ights/workspaces/myWorkspace/providers/Microsoft.SecurityInsights/alertRules/{myAlertRule}",
                   case_sensitive=False),
        test.check("name", "{myMetadata}", case_sensitive=False),
    ])
    step_metadata_list(test, checks=[
        test.check('length(@)', 1),
    ])
    step_metadata_list2(test, checks=[
        test.check('length(@)', 1),
    ])
    step_metadata_show(test, checks=[
        test.check("author.name", "User Name", case_sensitive=False),
        test.check("author.email", "email@microsoft.com", case_sensitive=False),
        test.check("contentId", "c00ee137-7475-47c8-9cce-ec6f0f1bedd0", case_sensitive=False),
        test.check("contentSchemaVersion", "2.0", case_sensitive=False),
        test.check("customVersion", "1.0", case_sensitive=False),
        test.check("firstPublishDate", "2021-05-18", case_sensitive=False),
        test.check("kind", "AnalyticsRule", case_sensitive=False),
        test.check("lastPublishDate", "2021-05-18", case_sensitive=False),
        test.check("parentId", "/subscriptions/{subscription_id}/resourceGroups/{rg}/providers/Microsoft.OperationalIns"
                   "ights/workspaces/myWorkspace/providers/Microsoft.SecurityInsights/alertRules/{myAlertRule}",
                   case_sensitive=False),
        test.check("source.name", "Contoso Solution 1.0", case_sensitive=False),
        test.check("source.kind", "Solution", case_sensitive=False),
        test.check("source.sourceId", "b688a130-76f4-4a07-bf57-762222a3cadf", case_sensitive=False),
        test.check("support.name", "Microsoft", case_sensitive=False),
        test.check("support.email", "support@microsoft.com", case_sensitive=False),
        test.check("support.link", "https://support.microsoft.com/", case_sensitive=False),
        test.check("support.tier", "Partner", case_sensitive=False),
        test.check("version", "1.0.0.0", case_sensitive=False),
        test.check("name", "{myMetadata}", case_sensitive=False),
    ])
    step_metadata_update(test, checks=[
        test.check("author.name", "User Name", case_sensitive=False),
        test.check("author.email", "email@microsoft.com", case_sensitive=False),
        test.check("contentId", "c00ee137-7475-47c8-9cce-ec6f0f1bedd0", case_sensitive=False),
        test.check("kind", "AnalyticsRule", case_sensitive=False),
        test.check("parentId", "/subscriptions/{subscription_id}/resourceGroups/{rg}/providers/Microsoft.OperationalIns"
                   "ights/workspaces/myWorkspace/providers/Microsoft.SecurityInsights/alertRules/{myAlertRule}",
                   case_sensitive=False),
        test.check("name", "{myMetadata}", case_sensitive=False),
    ])
    step_metadata_delete(test, checks=[])
    step_office_consent_list(test, checks=[])
    step_office_consent_show(test, checks=[])
    step_office_consent_delete(test, checks=[])
    step_product_setting_list(test, checks=[])
    step_product_setting_show(test, checks=[])
    step_product_setting_delete(test, checks=[])
    step_analytic_setting_create(test, checks=[])
    step_analytic_setting_show(test, checks=[])
    step_analytic_setting_list(test, checks=[])
    step_analytic_setting_delete(test, checks=[])
    step_onboarding_state_create(test, checks=[
        test.check("name", "{mySentinelOnboardingState}", case_sensitive=False),
        test.check("customerManagedKey", False),
    ])
    step_onboarding_state_list(test, checks=[
        test.check('length(@)', 1),
    ])
    step_onboarding_state_show(test, checks=[
        test.check("name", "{mySentinelOnboardingState}", case_sensitive=False),
        test.check("customerManagedKey", False),
    ])
    step_onboarding_state_delete(test, checks=[])
    step_source_control_list_repository(test, checks=[])
    step_source_control_create(test, checks=[])
    step_source_control_show(test, checks=[])
    step_source_control_list(test, checks=[])
    step_source_control_delete(test, checks=[])
    step_threat_indicator_update(test, checks=[])
    step_threat_indicator_show(test, checks=[])
    step_threat_indicator_append_tag(test, checks=[])
    step_threat_indicator_create(test, checks=[])
    step_threat_indicator_query(test, checks=[])
    step_threat_indicator_replace_tag(test, checks=[])
    step_threat_indicator_delete(test, checks=[])
    step_threat_indicator_metric_list(test, checks=[])
    step_threat_indicator_list(test, checks=[])
    step_watchlist_item_create(test, checks=[])
    step_watchlist_item_show(test, checks=[])
    step_watchlist_item_list(test, checks=[])
    step_watchlist_item_delete(test, checks=[])
    step_watchlist_create(test, checks=[])
    step_watchlist_create2(test, checks=[])
    step_watchlist_show(test, checks=[])
    step_watchlist_list(test, checks=[])
    step_watchlist_delete(test, checks=[])
    cleanup_scenario(test)


# Test class for Scenario
@try_manual
class SentinelScenarioTest(ScenarioTest):
    def __init__(self, *args, **kwargs):
        super(SentinelScenarioTest, self).__init__(*args, **kwargs)
        self.kwargs.update({
            'subscription_id': self.get_subscription_id()
        })

        self.kwargs.update({
            'myAlertRule': 'ruleName',
            'myIncident': 'afbd324f-6c48-459c-8710-8d1e1cd03812',
            'myBookmark': '2216d0e1-91e3-4902-89fd-d2df8c535096',
            'myMetadata': 'metadataName',
            'mySentinelOnboardingState': 'default',
        })

    @ResourceGroupPreparer(name_prefix='clitestsentinel_myRg'[:7], key='rg', parameter_name='rg')
    @ResourceGroupPreparer(name_prefix='clitestsentinel_ambawolvese5resourcegroup'[:7], key='rg_2',
                           parameter_name='rg_2')
    def test_sentinel_Scenario(self, rg, rg_2):
        call_scenario(self)
        calc_coverage(__file__)
        raise_if()
